on:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install pytest

      - name: run tests
        run: |
          cd lambda
          python -m pytest -v tests/unit --junitxml=junit/tests/lambda/test-results.xml
      
      - name: publish test results
        uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: test-results
          path: lambda/junit/tests/lambda/test-results.xml

  build-package:
    needs: run-tests
    runs-on: ubuntu-latest
    environment: package-release
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: set-up workspace
        run: |
          cd lambda
          make construct-directories
      - name: build-package
        run: |
          cd lambda
          make build-package
      - name: clean-up
        run: |
          cd lambda
          make clean-up